
// "use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {AppContextProvider} from "@/context/ClientContextProvider2.jsx";
import ClientContextProvider from "@/context/ClientContextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Recurring Date Picker App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
      <AppContextProvider>
        <ClientContextProvider>
        {children}
        </ClientContextProvider>
    </AppContextProvider>
      </body>

    </html>
  );
}
